// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnYwpe0V6PGorPHOwvjc5FVpazGdu6-Y',
    appId: '1:390509779972:web:5f01df843537f62e69a951',
    messagingSenderId: '390509779972',
    projectId: 'free-classroom-bf4b8',
    authDomain: 'free-classroom-bf4b8.firebaseapp.com',
    storageBucket: 'free-classroom-bf4b8.appspot.com',
    measurementId: 'G-G76PZ4D3RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgO9kUGCcwewT0M62hhISzOIuS2uW5WJg',
    appId: '1:390509779972:android:7e8f74fd7c92e1a269a951',
    messagingSenderId: '390509779972',
    projectId: 'free-classroom-bf4b8',
    storageBucket: 'free-classroom-bf4b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNRvudGWyN3mklB-6sn3YHfFYfYyFHas',
    appId: '1:390509779972:ios:a542ce4fa597af1f69a951',
    messagingSenderId: '390509779972',
    projectId: 'free-classroom-bf4b8',
    storageBucket: 'free-classroom-bf4b8.appspot.com',
    iosBundleId: 'com.example.freeclassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNRvudGWyN3mklB-6sn3YHfFYfYyFHas',
    appId: '1:390509779972:ios:a542ce4fa597af1f69a951',
    messagingSenderId: '390509779972',
    projectId: 'free-classroom-bf4b8',
    storageBucket: 'free-classroom-bf4b8.appspot.com',
    iosBundleId: 'com.example.freeclassroom',
  );
}
